In [34]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.api.types import is_object_dtype

In [35]:
df = pd.read_csv('drug200.csv')

In [36]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [38]:
df["Drug"].value_counts()

Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [28]:
for i in df.columns:
   if is_object_dtype(df[i]):
        print(f"{i} = {df[i].unique()}")

Sex = ['F' 'M']
BP = ['HIGH' 'LOW' 'NORMAL']
Cholesterol = ['HIGH' 'NORMAL']
Drug = ['DrugY' 'drugC' 'drugX' 'drugA' 'drugB']

In [30]:
for col in df.columns:
   if is_object_dtype(df[col]):
        df = pd.get_dummies(df,columns=[col],drop_first=True)

In [31]:
df.head()

,Age,Na_to_K,Sex_M,BP_LOW,BP_NORMAL,Cholesterol_NORMAL,Drug_drugA,Drug_drugB,Drug_drugC,Drug_drugX
0,23,25.355,False,False,False,False,False,False,False,False
1,47,13.093,True,True,False,False,False,False,True,False
2,47,10.114,True,True,False,False,False,False,True,False
3,28,7.798,False,False,True,False,False,False,False,True
4,61,18.043,False,True,False,False,False,False,False,False

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 200 non-null    int64
 1   Na_to_K             200 non-null    float64
 2   Sex_M               200 non-null    bool
 3   BP_LOW              200 non-null    bool
 4   BP_NORMAL           200 non-null    bool
 5   Cholesterol_NORMAL  200 non-null    bool
 6   Drug_drugA          200 non-null    bool
 7   Drug_drugB          200 non-null    bool
 8   Drug_drugC          200 non-null    bool
 9   Drug_drugX          200 non-null    bool
dtypes: bool(8), float64(1), int64(1)
memory usage: 4.8 KB