In [91]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.api.types import is_object_dtype

In [92]:
df = pd.read_csv('drug200.csv')

In [93]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [95]:
df["Drug"].value_counts()

Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [96]:
for i in df.columns:
   if is_object_dtype(df[i]):
        print(f"{i} = {df[i].unique()}")

Sex = ['F' 'M']
BP = ['HIGH' 'LOW' 'NORMAL']
Cholesterol = ['HIGH' 'NORMAL']
Drug = ['DrugY' 'drugC' 'drugX' 'drugA' 'drugB']

In [97]:
for col in df.columns:
   if is_object_dtype(df[col]) and col != "Drug":
        df = pd.get_dummies(df,columns=[col],drop_first=True)

In [98]:
df.head()

   Age  Na_to_K   Drug  Sex_M  BP_LOW  BP_NORMAL  Cholesterol_NORMAL
0   23   25.355  DrugY  False   False      False               False
1   47   13.093  drugC   True    True      False               False
2   47   10.114  drugC   True    True      False               False
3   28    7.798  drugX  False   False       True               False
4   61   18.043  DrugY  False    True      False               False

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 200 non-null    int64
 1   Na_to_K             200 non-null    float64
 2   Drug                200 non-null    object
 3   Sex_M               200 non-null    bool
 4   BP_LOW              200 non-null    bool
 5   BP_NORMAL           200 non-null    bool
 6   Cholesterol_NORMAL  200 non-null    bool
dtypes: bool(4), float64(1), int64(1), object(1)
memory usage: 5.6+ KB

In [100]:
X = df.drop("Drug",axis=1)
y = df["Drug"]

In [101]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=5)

In [102]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    multi_class='multinomial',  # ÇOK ÖNEMLİ!
    solver='lbfgs',              # multinomial için uygun solver
    max_iter=2000,
    random_state=42
)
model.fit(X_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, multi_class='multinomial', random_state=42)

In [103]:
y_pred = model.predict(X_test)

In [104]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Doğruluk:", accuracy_score(y_test, y_pred))
print("\nDetaylı Rapor:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Doğruluk: 1.0

Detaylı Rapor:
               precision    recall  f1-score   support

       DrugY       1.00      1.00      1.00        27
       drugA       1.00      1.00      1.00         3
       drugB       1.00      1.00      1.00         4
       drugC       1.00      1.00      1.00         5
       drugX       1.00      1.00      1.00        11

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50


Confusion Matrix:
 [[27  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0  5  0]
 [ 0  0  0  0 11]]

In [105]:
df.head()

   Age  Na_to_K   Drug  Sex_M  BP_LOW  BP_NORMAL  Cholesterol_NORMAL
0   23   25.355  DrugY  False   False      False               False
1   47   13.093  drugC   True    True      False               False
2   47   10.114  drugC   True    True      False               False
3   28    7.798  drugX  False   False       True               False
4   61   18.043  DrugY  False    True      False               False

In [106]:
model.predict([[25,8,False,True,True,False]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['drugX'], dtype=object)

In [1]:
import joblib

In [2]:
joblib.load("drug_model.pkl")

LogisticRegression()